/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import dao.DanhMucSachDAO;
import dao.DonHangCTDAO;
import dao.DonHangDAO;
import dao.SachDAO;
import java.awt.Color;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.print.DocPrintJob;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;
import phuongtien.Auth;
import phuongtien.MsgBox;
import phuongtien.XDate;
import phuongtien.XImage;
import thucthe.DanhMucSach;
import thucthe.DonHang;
import thucthe.DonHangCT;
import thucthe.Sach;

/**
 *
 * @author Thanh Lam
 */
public class DonHangJDialog extends javax.swing.JDialog {

    DanhMucSachDAO lsDAO = new DanhMucSachDAO();
    DonHangDAO dhDAO = new DonHangDAO();
    DonHangCTDAO dhctDAO = new DonHangCTDAO();
    SachDAO sDAO = new SachDAO();
    int row = 0;
    int maDhct = 0;

    /**
     * Creates new form DonHangJDialog
     */
    public DonHangJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popup_TrangThai = new javax.swing.JPopupMenu();
        mnuTrangThai = new javax.swing.JMenu();
        mniDangXuLy = new javax.swing.JMenuItem();
        mniHuyDon = new javax.swing.JMenuItem();
        mniChotDon = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        cbxLoaiSach = new javax.swing.JComboBox<>();
        btnThanhToan = new javax.swing.JButton();
        btnLamMoi = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtMaDH = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtMaLS = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtNgayMua = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtTenS = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtMaS = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtGiaTien = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtSoLuong = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtGhiChu = new javax.swing.JTextArea();
        jLabel20 = new javax.swing.JLabel();
        txtTongTien = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblSach = new javax.swing.JTable();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        btnTimkiem = new javax.swing.JButton();
        txtTimkiem = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDonHangCT = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblDonHang = new javax.swing.JTable();
        btnCapNhat = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();

        mnuTrangThai.setText("Trạng Thái");
        mnuTrangThai.setToolTipText("");

        mniDangXuLy.setText("Đang xử lý");
        mniDangXuLy.setToolTipText("");
        mniDangXuLy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDangXuLyActionPerformed(evt);
            }
        });
        mnuTrangThai.add(mniDangXuLy);

        mniHuyDon.setText("Hủy đơn");
        mniHuyDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniHuyDonActionPerformed(evt);
            }
        });
        mnuTrangThai.add(mniHuyDon);

        mniChotDon.setText("Chốt đơn");
        mniChotDon.setToolTipText("");
        mniChotDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniChotDonActionPerformed(evt);
            }
        });
        mnuTrangThai.add(mniChotDon);

        popup_TrangThai.add(mnuTrangThai);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("HOPE - QUẢN LÝ ĐƠN HÀNG");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51), 5));

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        jPanel4.setBackground(new java.awt.Color(0, 153, 153));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2), "LOẠI SÁCH", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        cbxLoaiSach.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cbxLoaiSach.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        cbxLoaiSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxLoaiSachActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addComponent(cbxLoaiSach, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cbxLoaiSach, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        btnThanhToan.setBackground(new java.awt.Color(255, 51, 51));
        btnThanhToan.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnThanhToan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hinhanh/sell_48px.png"))); // NOI18N
        btnThanhToan.setText("Thanh toán");
        btnThanhToan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        btnThanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThanhToanActionPerformed(evt);
            }
        });

        btnLamMoi.setBackground(new java.awt.Color(255, 153, 51));
        btnLamMoi.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnLamMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hinhanh/refresh_48px.png"))); // NOI18N
        btnLamMoi.setText("Làm mới");
        btnLamMoi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Mã đơn hàng ");

        jLabel13.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Ngày mua");

        jLabel14.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Mã loại sách");

        jLabel15.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Mã sách");

        jLabel16.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Tên sách");

        jLabel17.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Số lượng");

        jLabel18.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText(" Giá tiền");

        txtSoLuong.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSoLuongFocusLost(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Ghi chú");

        txtGhiChu.setColumns(20);
        txtGhiChu.setRows(5);
        jScrollPane2.setViewportView(txtGhiChu);

        jLabel20.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Tổng tiền");

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        tblSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "MÃ SÁCH", "TÊN SÁCH", "TÁC GIẢ", "SỐ LƯỢNG HIỆN CÓ", "GiÁ TIỀN"
            }
        ));
        tblSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblSachMousePressed(evt);
            }
        });
        jScrollPane3.setViewportView(tblSach);
        if (tblSach.getColumnModel().getColumnCount() > 0) {
            tblSach.getColumnModel().getColumn(0).setResizable(false);
            tblSach.getColumnModel().getColumn(0).setPreferredWidth(5);
            tblSach.getColumnModel().getColumn(1).setResizable(false);
            tblSach.getColumnModel().getColumn(1).setPreferredWidth(150);
            tblSach.getColumnModel().getColumn(2).setResizable(false);
            tblSach.getColumnModel().getColumn(2).setPreferredWidth(100);
            tblSach.getColumnModel().getColumn(3).setResizable(false);
            tblSach.getColumnModel().getColumn(3).setPreferredWidth(5);
            tblSach.getColumnModel().getColumn(4).setResizable(false);
            tblSach.getColumnModel().getColumn(4).setPreferredWidth(10);
        }

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jSeparator2)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(btnLamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel14)
                                .addComponent(jLabel16))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel18))
                                .addGap(40, 40, 40)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtMaLS)
                                    .addComponent(txtMaDH)
                                    .addComponent(txtTenS)
                                    .addComponent(txtGiaTien, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(83, 83, 83)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel20)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel17)
                                            .addComponent(jLabel15))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNgayMua)
                                    .addComponent(txtMaS)
                                    .addComponent(txtSoLuong)
                                    .addComponent(txtTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 631, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 774, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMaDH, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtNgayMua, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMaLS, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMaS, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTenS, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtGiaTien, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(jLabel18))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThanhToan)
                    .addComponent(btnLamMoi))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Thông tin đơn hàng ", new javax.swing.ImageIcon(getClass().getResource("/hinhanh/order_history_48px.png")), jPanel2); // NOI18N

        jPanel3.setBackground(new java.awt.Color(0, 153, 153));

        btnTimkiem.setBackground(new java.awt.Color(255, 153, 51));
        btnTimkiem.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnTimkiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hinhanh/search_48px.png"))); // NOI18N
        btnTimkiem.setText("Tìm kiếm");
        btnTimkiem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        btnTimkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimkiemActionPerformed(evt);
            }
        });

        txtTimkiem.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtTimkiem.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtTimkiem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153), 3));
        txtTimkiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTimkiemKeyPressed(evt);
            }
        });

        tblDonHangCT.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153), 3));
        tblDonHangCT.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tblDonHangCT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "MÃ ĐƠN HÀNG", "MÃ  ĐƠN HÀNG CT", "MÃ LOẠI SÁCH", "MÃ SÁCH", "TÊN SÁCH", "SL MUA", "GIÁ TIỀN", "TỔNG TIỀN", "GHI CHÚ"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, true, false, true, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDonHangCT.setRowHeight(30);
        tblDonHangCT.setSelectionBackground(new java.awt.Color(0, 166, 245));
        tblDonHangCT.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(tblDonHangCT);

        tblDonHang.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)));
        tblDonHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "MÃ ĐH", "TỔNG TIỀN", "NGÀY MUA", "TRẠNG THÁI", "MÃ NV"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDonHang.setComponentPopupMenu(popup_TrangThai);
        tblDonHang.setRowHeight(30);
        tblDonHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblDonHangMousePressed(evt);
            }
        });
        jScrollPane4.setViewportView(tblDonHang);

        btnCapNhat.setBackground(new java.awt.Color(255, 153, 51));
        btnCapNhat.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnCapNhat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hinhanh/update_48px.png"))); // NOI18N
        btnCapNhat.setText("Cập nhật trạng thái");
        btnCapNhat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 786, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 786, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 783, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(btnCapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addComponent(txtTimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(btnTimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTimkiem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(btnCapNhat)
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(180, 180, 180))
        );

        jTabbedPane1.addTab("Danh sách đơn hàng ", new javax.swing.ImageIcon(getClass().getResource("/hinhanh/list_of_thumbnails_48px.png")), jPanel3); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 761, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 781, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 219, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        clearForm();
    }//GEN-LAST:event_btnLamMoiActionPerformed

    private void btnThanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThanhToanActionPerformed
        if (validateForm() == true) {
            if (dhDAO.selectById(txtMaDH.getText()) != null) {
                updateDH();
                insertDonHangCT();
                MsgBox.alertSuccessful(this, "Thanh toán đơn hàng thành công");
            } else {
                insertDonHang();
                insertDonHangCT();
                this.clearForm();
            }
        } else {
            MsgBox.alert(this, "Vui lòng điền đủ thông tin và chính xác");
        }

    }//GEN-LAST:event_btnThanhToanActionPerformed

    private void cbxLoaiSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxLoaiSachActionPerformed
        chonLoaiSach();

    }//GEN-LAST:event_cbxLoaiSachActionPerformed

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
        try {
            String trThai = tblDonHang.getValueAt(row, 3).toString();
            updateTrangThai();

        } catch (NumberFormatException e) {
            MsgBox.alert(this, "Cập nhật lại.");
        }
    }//GEN-LAST:event_btnCapNhatActionPerformed

    private void tblSachMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSachMousePressed
        if (evt.getClickCount() == 2) {
            this.row = tblSach.rowAtPoint(evt.getPoint());
            this.edit();
        }
    }//GEN-LAST:event_tblSachMousePressed

    private void tblDonHangMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDonHangMousePressed
        if (evt.getClickCount() == 2) {
            this.row = tblDonHang.rowAtPoint(evt.getPoint());

            this.fillTableDonHangCT();

        }

    }//GEN-LAST:event_tblDonHangMousePressed

    private void txtSoLuongFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSoLuongFocusLost
        try {
            double soLuong = Double.parseDouble(txtSoLuong.getText());
            double gia = Double.parseDouble(txtGiaTien.getText());
            if (soLuong < 0) {
                return;
            }
            if (gia <= 0) {
                return;
            }
            double tong = soLuong * gia;
            txtTongTien.setText(tong + "");
        } catch (Exception e) {

            return;
        }

    }//GEN-LAST:event_txtSoLuongFocusLost

    private void btnTimkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimkiemActionPerformed

        this.fillTableDonHang();
        this.fillTableDonHangCT();


    }//GEN-LAST:event_btnTimkiemActionPerformed

    private void txtTimkiemKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimkiemKeyPressed
        this.fillTableDonHang();
        this.fillTableDonHangCT();
    }//GEN-LAST:event_txtTimkiemKeyPressed

    private void mniDangXuLyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDangXuLyActionPerformed
        int row = tblDonHang.getSelectedRow();

        if (row >= 0)
            tblDonHang.setValueAt("Đang xử lý", row, 3);
    }//GEN-LAST:event_mniDangXuLyActionPerformed

    private void mniHuyDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniHuyDonActionPerformed
        int row = tblDonHang.getSelectedRow();

        if (row >= 0) {
            tblDonHang.setValueAt("Hủy đơn", row, 3);
        }

    }//GEN-LAST:event_mniHuyDonActionPerformed

    private void mniChotDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniChotDonActionPerformed
        int row = tblDonHang.getSelectedRow();

        if (row >= 0) {
            tblDonHang.setValueAt("Chốt đơn", row, 3);
        }

    }//GEN-LAST:event_mniChotDonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DonHangJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DonHangJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DonHangJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DonHangJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DonHangJDialog dialog = new DonHangJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnThanhToan;
    private javax.swing.JButton btnTimkiem;
    private javax.swing.JComboBox<String> cbxLoaiSach;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JMenuItem mniChotDon;
    private javax.swing.JMenuItem mniDangXuLy;
    private javax.swing.JMenuItem mniHuyDon;
    private javax.swing.JMenu mnuTrangThai;
    private javax.swing.JPopupMenu popup_TrangThai;
    private javax.swing.JTable tblDonHang;
    private javax.swing.JTable tblDonHangCT;
    private javax.swing.JTable tblSach;
    private javax.swing.JTextArea txtGhiChu;
    private javax.swing.JTextField txtGiaTien;
    private javax.swing.JTextField txtMaDH;
    private javax.swing.JTextField txtMaLS;
    private javax.swing.JTextField txtMaS;
    private javax.swing.JTextField txtNgayMua;
    private javax.swing.JTextField txtSoLuong;
    private javax.swing.JTextField txtTenS;
    private javax.swing.JTextField txtTimkiem;
    private javax.swing.JTextField txtTongTien;
    // End of variables declaration//GEN-END:variables

    private void init() {
        setSize(900, 1000);
        setLocationRelativeTo(null);
        this.setIconImage(XImage.getLogo());
        this.fillComboBoxLoaiSach();
        this.fillTableSach();
        this.fillTableDonHang();
        this.fillTableDonHangCT();
    }

    void fillComboBoxLoaiSach() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) cbxLoaiSach.getModel();
        model.removeAllElements();
        List<DanhMucSach> list = lsDAO.selectAll();
        for (DanhMucSach ls : list) {
            model.addElement(ls);
        }
    }

    private void chonLoaiSach() {
        DanhMucSach dms = (DanhMucSach) cbxLoaiSach.getSelectedItem();
        if (dms != null) {
            this.fillTableSach();
            this.row = 0;
        }

        //this.updateStatus();
    }

    void fillTableSach() {
        //Đổ dữ liệu vào bảng
        DefaultTableModel model = (DefaultTableModel) tblSach.getModel();
        model.setRowCount(0);//Xóa tất cả các hàng trên Jtable

        try {

            DanhMucSach dms = (DanhMucSach) cbxLoaiSach.getSelectedItem();
            if (dms != null) {
                List<Sach> list = sDAO.selectByLoaiSachDH(dms.getMaLoaiSach());
                for (Sach s : list) {

                    model.addRow(new Object[]{
                        s.getMaSach(),
                        s.getTenSach(),
                        s.getTacGia(),
                        s.getSoLuong(),
                        String.format("%.0f", s.getGiaBan())+" đ"
                    });
                }
            }
        } catch (Exception e) {
            MsgBox.alert(this, "Lỗi truy vấn dữ liệu!");
            e.printStackTrace();
        }

    }

    void setFormSach(Sach model) {
        txtMaLS.setText(model.getMaLoaiSach());
        txtMaS.setText(String.valueOf(model.getMaSach()));
        txtTenS.setText(model.getTenSach());
        txtGiaTien.setText(String.valueOf(model.getGiaBan()));
    }

    void clearForm() {
        this.setFormSach(new Sach());
        //this.setFormDH(new DonHang());
        this.setFormDHCT(new DonHangCT());
        txtTongTien.setText("");
        row = 0;
        //updateStatus();
    }

    void edit() {
        try {
            int maSach = (int) tblSach.getValueAt(row, 0);
            Sach s = sDAO.selectById(maSach);
            if (s != null) {
                setFormSach(s);
            }
        } catch (Exception e) {
            MsgBox.alert(this, "Lỗi truy vấn dữ liệu !");
        }
    }

    void fillTableDonHang() {
        //Đổ dữ liệu vào bảng
        DefaultTableModel model = (DefaultTableModel) tblDonHang.getModel();
        model.setRowCount(0);//Xóa tất cả các hàng trên Jtable

        try {
            String maDH = txtTimkiem.getText();

            List<DonHang> list = dhDAO.selectByTong(maDH);
            for (DonHang dh : list) {
                model.addRow(new Object[]{
                    dh.getMaDH(),
                    String.format("%.0f", dh.getTongTien())+" đ",
                    dh.getNgayMua(),
                    dh.getTrangThai(),
                    dh.getMaNV()
                });
            }
        } catch (Exception e) {
            MsgBox.alert(this, "Lỗi truy vấn dữ liệu!");
            e.printStackTrace();
        }

    }

    void fillTableDonHangCT() {
        //Đổ dữ liệu vào bảng
        DefaultTableModel model = (DefaultTableModel) tblDonHangCT.getModel();
        model.setRowCount(0);//Xóa tất cả các hàng trên Jtable

        try {
            String dhct = txtTimkiem.getText();
            List<DonHangCT> list = dhctDAO.selectByKeywordCT(dhct);
            for (DonHangCT ct : list) {

                model.addRow(new Object[]{
                    ct.getMaDH(),
                    ct.getMaDHCT(),
                    ct.getMaLs(),
                    ct.getMaS(),
                    ct.getTenS(),
                    ct.getSoLuong(),
                    String.format("%.0f", ct.getGiaBan())+" đ",
                    String.format("%.0f", ct.getTongTienCT())+ " đ",
                    ct.getGhiChu()

                });
            }
        } catch (Exception e) {
            MsgBox.alert(this, "Lỗi truy vấn dữ liệu!");
            e.printStackTrace();
        }

    }

    DonHang getForm() {
        DonHang model = new DonHang();
        model.setMaDH(txtMaDH.getText());
        model.setNgayMua(XDate.toDate(txtNgayMua.getText(), "dd-MM-yyyy"));
        model.setMaNV(Auth.user.getMaNhanVien());
        return model;
    }

    DonHangCT getFormCT() {
        DonHangCT ct = new DonHangCT();
        ct.setMaDH(txtMaDH.getText());
        ct.setMaDHCT(maDhct);
        ct.setMaLs(txtMaLS.getText());
        ct.setMaS(Integer.parseInt(txtMaS.getText()));
        ct.setTenS(txtTenS.getText());
        ct.setSoLuong(Integer.parseInt(txtSoLuong.getText()));
        ct.setGiaBan(Double.parseDouble(txtGiaTien.getText()));
        ct.setGhiChu(txtGhiChu.getText());
        return ct;
    }

    void insertDonHang() {

        DonHang dh = getForm();
        if (txtMaDH.getText().equals(dh.getMaDH())) {
            try {
                dhDAO.insert(dh);
                this.fillTableDonHang();// đổ dữ liệu vào bảng
                //this.clearForm();// sau khi thêm xong thì ta xóa trắng form
                MsgBox.alertSuccessful(this, "Đơn hàng thanh toán thành công!");
            } catch (Exception e) {
                MsgBox.alert(this, "Đơn hàng thanh toán thất bại!");
                e.printStackTrace();
            }
        }
    }

    void updateDH() {

        DonHang dh = getForm();
        try {
            dhDAO.update(dh);
            this.fillTableDonHang();
            //MsgBox.alertSuccessful(this, "Cập nhật Đơn hàng thành công !");
        } catch (Exception e) {
            //MsgBox.alert(this, "Cập nhật Đơn hàng thất bại !");
        }
    }

    void updateTrangThai() {
        for (int i = 0; i < tblDonHang.getRowCount(); i++) {
            String maDh = (String) tblDonHang.getValueAt(i, 0);
            DonHang dh = dhDAO.selectById(maDh);
            dh.setTrangThai((String) tblDonHang.getValueAt(i, 3));
            dhDAO.update(dh);

        }
        MsgBox.alertSuccessful(this, "Cập nhật thành công!");
    }

    void insertDonHangCT() {

        DonHangCT dhct = getFormCT();
        try {
            dhct.setMaDHCT(maDhct);
            System.out.println("" + dhct.getMaS());
            dhctDAO.insert(dhct);
            sDAO.update(dhct.getSoLuong(), dhct.getMaS());
            // System.out.println("soluong " + dhct.getSoLuong()+ " " + dhct.getMaS());
            this.fillTableSach();
            this.fillTableDonHangCT(); // đổ dữ liệu vào bảng
            //this.clearForm();// sau khi thêm xong thì ta xóa trắng form

            //MsgBox.alertSuccessful(this, "Đơn hàng chi tiết thanh toán thành công!");
        } catch (Exception e) {
            //MsgBox.alert(this, "Đơn hàng chi tiết thanh toán thất bại!");
            e.printStackTrace();
        }

    }

    /* void setFormDH(DonHang model) {
        txtMaDH.setText(model.getMaDH());
        Date d = model.getNgayMua();
        if (d != null) {
            txtNgayMua.setText(XDate.toString(model.getNgayMua(), "dd-MM-yyyy"));
        } else {
            txtNgayMua.setText("");
        }
    }*/
    void setFormDHCT(DonHangCT model) {

        txtMaLS.setText(model.getMaLs());
        txtMaS.setText(String.valueOf(model.getMaS()));
        txtTenS.setText(model.getTenS());
        txtSoLuong.setText(String.valueOf(model.getSoLuong()));
        txtGiaTien.setText(String.valueOf(model.getGiaBan()));
        txtGhiChu.setText(model.getGhiChu());
    }

    boolean validateForm() {
        if (txtMaDH.getText().equals("")) {
            MsgBox.alert(this, "Bạn chưa nhập Mã đơn hàng!");
            txtMaDH.setBackground(Color.red);
            return false;
        } else {
            txtMaDH.setBackground(Color.white);
        }

        if (txtNgayMua.getText().equals("")) {
            MsgBox.alert(this, "Bạn chưa nhập ngày tháng năm!");
            txtNgayMua.setBackground(Color.red);
            return false;
        } else {
            txtNgayMua.setBackground(Color.white);
        }

        if (txtMaLS.getText().equals("")) {
            MsgBox.alert(this, "Bạn chưa nhập Mã loại sách!");
            txtMaLS.setBackground(Color.red);
            return false;
        } else {
            txtMaLS.setBackground(Color.white);
        }
        
        if (txtMaS.getText().equals("")) {
            MsgBox.alert(this, "Bạn chưa nhập Mã sách !");
            txtMaS.setBackground(Color.red);
            return false;
        } else {
            txtMaS.setBackground(Color.white);
        }

        if (txtTenS.getText().equals("")) {
            MsgBox.alert(this, "Bạn chưa nhập tên sách !");
            txtTenS.setBackground(Color.red);
            return false;  
        }else{
            txtTenS.setBackground(Color.white);}

        if (txtSoLuong.getText().equals("")) {
            MsgBox.alert(this, "Bạn chưa nhập số lượng mua !");
            txtSoLuong.setBackground(Color.red);
            return false;  
        }else{
            txtSoLuong.setBackground(Color.white);}
        
        if (txtGiaTien.getText().equals("")) {
            MsgBox.alert(this, "Bạn chưa nhập giá tiền!");
            txtGiaTien.setBackground(Color.red);
            return false;  
        }else{
            txtGiaTien.setBackground(Color.white);}

        Pattern pattern = Pattern.compile("^(0?[1-9]|[12][0-9]|3[01])[\\/\\-](0?[1-9]|1[012])[\\/\\-]\\d{4}$");
        Matcher matcher = pattern.matcher(txtNgayMua.getText());
        if (!matcher.find()) {
            MsgBox.alert(this, "Ngày tháng năm không hợp lệ !");
            txtNgayMua.setBackground(Color.red);
            return false;
        }
        try {
            double soLuong = Double.parseDouble(txtSoLuong.getText());
            if (soLuong < 0) {
                MsgBox.alert(this, "Số lượng không được âm !");
                txtSoLuong.setBackground(Color.red);
                return false;
            }
        } catch (Exception e) {
            MsgBox.alert(this, "Số lượng phải là số !");
            txtSoLuong.setBackground(Color.red);
            return false;
        }
        try {
            double gia = Double.parseDouble(txtGiaTien.getText());
            if (gia <= 0) {
                MsgBox.alert(this, "Giá tiền phải lớn hơn 0 !");
                txtGiaTien.setBackground(Color.red);
                return false;
            }
        } catch (Exception e) {
            MsgBox.alert(this, "Giá tiền phải là số !");
            txtGiaTien.setBackground(Color.red);
            return false;
        }
        return true;
    }

}
