/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.Timer;
import phuongtien.Auth;
import phuongtien.MsgBox;
import phuongtien.XImage;

/**
 *
 * @author Thanh Lam
 */
public class TrangChuJFrame extends javax.swing.JFrame {

    /**
     * Creates new form TrangChuJFrame
     */
    public TrangChuJFrame() {
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        btnTaiNguyen = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        btnDonHang = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JToolBar.Separator();
        btnTopSach = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        btnDangXuat = new javax.swing.JButton();
        jSeparator8 = new javax.swing.JToolBar.Separator();
        btnKetThuc = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lblDongHo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mniDangXuat = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mniDoiMatKhau = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        mniKetThuc = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mniSach = new javax.swing.JMenuItem();
        mniDonHang = new javax.swing.JMenuItem();
        mniDanhMuc = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mniNhanVien = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mniTopSach = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        mniDoanhThu = new javax.swing.JMenuItem();
        mnuGioiThieu = new javax.swing.JMenu();
        mniGioiThieu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HOPE - TRANG CHỦ");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 229, 210), 5));

        jToolBar1.setBackground(new java.awt.Color(255, 255, 255));
        jToolBar1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jToolBar1.setRollover(true);
        jToolBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btnTaiNguyen.setBackground(new java.awt.Color(255, 255, 255));
        btnTaiNguyen.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        btnTaiNguyen.setForeground(new java.awt.Color(0, 153, 153));
        btnTaiNguyen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hinhanh/books_48px.png"))); // NOI18N
        btnTaiNguyen.setText("Tài nguyên");
        btnTaiNguyen.setBorder(null);
        btnTaiNguyen.setFocusable(false);
        btnTaiNguyen.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTaiNguyen.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnTaiNguyen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaiNguyenActionPerformed(evt);
            }
        });
        jToolBar1.add(btnTaiNguyen);
        jToolBar1.add(jSeparator6);

        btnDonHang.setBackground(new java.awt.Color(255, 255, 255));
        btnDonHang.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        btnDonHang.setForeground(new java.awt.Color(0, 153, 153));
        btnDonHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hinhanh/bookshop_48px.png"))); // NOI18N
        btnDonHang.setText("Đơn hàng");
        btnDonHang.setBorder(null);
        btnDonHang.setFocusable(false);
        btnDonHang.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDonHang.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDonHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDonHangActionPerformed(evt);
            }
        });
        jToolBar1.add(btnDonHang);
        jToolBar1.add(jSeparator7);

        btnTopSach.setBackground(new java.awt.Color(255, 255, 255));
        btnTopSach.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        btnTopSach.setForeground(new java.awt.Color(0, 153, 153));
        btnTopSach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hinhanh/fire_48px.png"))); // NOI18N
        btnTopSach.setText("Top sách");
        btnTopSach.setBorder(null);
        btnTopSach.setFocusable(false);
        btnTopSach.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTopSach.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnTopSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTopSachActionPerformed(evt);
            }
        });
        jToolBar1.add(btnTopSach);
        jToolBar1.add(jSeparator5);

        btnDangXuat.setBackground(new java.awt.Color(255, 255, 255));
        btnDangXuat.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        btnDangXuat.setForeground(new java.awt.Color(0, 153, 153));
        btnDangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hinhanh/exit_40px.png"))); // NOI18N
        btnDangXuat.setText("Đăng xuất");
        btnDangXuat.setBorder(null);
        btnDangXuat.setFocusable(false);
        btnDangXuat.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDangXuat.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangXuatActionPerformed(evt);
            }
        });
        jToolBar1.add(btnDangXuat);
        jToolBar1.add(jSeparator8);

        btnKetThuc.setBackground(new java.awt.Color(255, 255, 255));
        btnKetThuc.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        btnKetThuc.setForeground(new java.awt.Color(0, 153, 153));
        btnKetThuc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hinhanh/cancel_48px.png"))); // NOI18N
        btnKetThuc.setText("Kết thúc");
        btnKetThuc.setBorder(null);
        btnKetThuc.setFocusable(false);
        btnKetThuc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnKetThuc.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnKetThuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKetThucActionPerformed(evt);
            }
        });
        jToolBar1.add(btnKetThuc);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hinhanh/original_work-hard-typographic-print.jpg"))); // NOI18N

        lblDongHo.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        lblDongHo.setForeground(new java.awt.Color(0, 153, 153));
        lblDongHo.setText("6:39:00");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblDongHo)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)))
                .addGap(0, 8, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblDongHo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));

        jMenu1.setBackground(new java.awt.Color(255, 255, 255));
        jMenu1.setForeground(new java.awt.Color(0, 153, 153));
        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hinhanh/account_40px.png"))); // NOI18N
        jMenu1.setText("Tài khoản");
        jMenu1.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N

        mniDangXuat.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniDangXuat.setBackground(new java.awt.Color(255, 255, 255));
        mniDangXuat.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        mniDangXuat.setForeground(new java.awt.Color(0, 153, 153));
        mniDangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hinhanh/exit_40px.png"))); // NOI18N
        mniDangXuat.setText("Đăng xuất");
        mniDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDangXuatActionPerformed(evt);
            }
        });
        jMenu1.add(mniDangXuat);
        jMenu1.add(jSeparator2);

        mniDoiMatKhau.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniDoiMatKhau.setBackground(new java.awt.Color(255, 255, 255));
        mniDoiMatKhau.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        mniDoiMatKhau.setForeground(new java.awt.Color(0, 153, 153));
        mniDoiMatKhau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hinhanh/book_16px.png"))); // NOI18N
        mniDoiMatKhau.setText("Đổi mật khẩu");
        mniDoiMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDoiMatKhauActionPerformed(evt);
            }
        });
        jMenu1.add(mniDoiMatKhau);
        jMenu1.add(jSeparator3);

        mniKetThuc.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniKetThuc.setBackground(new java.awt.Color(255, 255, 255));
        mniKetThuc.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        mniKetThuc.setForeground(new java.awt.Color(0, 153, 153));
        mniKetThuc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hinhanh/cancel_48px.png"))); // NOI18N
        mniKetThuc.setText("Kết thúc ");
        mniKetThuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniKetThucActionPerformed(evt);
            }
        });
        jMenu1.add(mniKetThuc);

        jMenuBar1.add(jMenu1);

        jMenu2.setForeground(new java.awt.Color(0, 153, 153));
        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hinhanh/merge_horizontal_40px.png"))); // NOI18N
        jMenu2.setText("Quản lý");
        jMenu2.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N

        mniSach.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_K, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniSach.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        mniSach.setForeground(new java.awt.Color(0, 153, 153));
        mniSach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hinhanh/books_48px.png"))); // NOI18N
        mniSach.setText("Sách");
        mniSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniSachActionPerformed(evt);
            }
        });
        jMenu2.add(mniSach);

        mniDonHang.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniDonHang.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        mniDonHang.setForeground(new java.awt.Color(0, 153, 153));
        mniDonHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hinhanh/bookshop_48px.png"))); // NOI18N
        mniDonHang.setText("Đơn hàng");
        mniDonHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDonHangActionPerformed(evt);
            }
        });
        jMenu2.add(mniDonHang);

        mniDanhMuc.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniDanhMuc.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        mniDanhMuc.setForeground(new java.awt.Color(0, 153, 153));
        mniDanhMuc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hinhanh/book_48px.png"))); // NOI18N
        mniDanhMuc.setText("Danh mục sách");
        mniDanhMuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDanhMucActionPerformed(evt);
            }
        });
        jMenu2.add(mniDanhMuc);
        jMenu2.add(jSeparator1);

        mniNhanVien.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniNhanVien.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        mniNhanVien.setForeground(new java.awt.Color(0, 153, 153));
        mniNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hinhanh/staff_48px.png"))); // NOI18N
        mniNhanVien.setText("Nhân viên");
        mniNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniNhanVienActionPerformed(evt);
            }
        });
        jMenu2.add(mniNhanVien);

        jMenuBar1.add(jMenu2);

        jMenu3.setForeground(new java.awt.Color(0, 153, 153));
        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hinhanh/statistics_48px.png"))); // NOI18N
        jMenu3.setText("Thống kê");
        jMenu3.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N

        mniTopSach.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniTopSach.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        mniTopSach.setForeground(new java.awt.Color(0, 153, 153));
        mniTopSach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hinhanh/fire_48px.png"))); // NOI18N
        mniTopSach.setText("Top sách bán chạy");
        mniTopSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniTopSachActionPerformed(evt);
            }
        });
        jMenu3.add(mniTopSach);
        jMenu3.add(jSeparator4);

        mniDoanhThu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.ALT_DOWN_MASK));
        mniDoanhThu.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        mniDoanhThu.setForeground(new java.awt.Color(0, 153, 153));
        mniDoanhThu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hinhanh/cash_40px.png"))); // NOI18N
        mniDoanhThu.setText("Doanh thu");
        mniDoanhThu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDoanhThuActionPerformed(evt);
            }
        });
        jMenu3.add(mniDoanhThu);

        jMenuBar1.add(jMenu3);

        mnuGioiThieu.setForeground(new java.awt.Color(0, 153, 153));
        mnuGioiThieu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hinhanh/name_tag_48px.png"))); // NOI18N
        mnuGioiThieu.setText("Giới thiệu");
        mnuGioiThieu.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N

        mniGioiThieu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniGioiThieu.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        mniGioiThieu.setForeground(new java.awt.Color(0, 153, 153));
        mniGioiThieu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hinhanh/name_tag_48px.png"))); // NOI18N
        mniGioiThieu.setText("Giới thiệu");
        mniGioiThieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniGioiThieuActionPerformed(evt);
            }
        });
        mnuGioiThieu.add(mniGioiThieu);

        jMenuBar1.add(mnuGioiThieu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mniKetThucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniKetThucActionPerformed
        if (MsgBox.confirm(this, "Bạn muốn kết thúc làm việc ?")) {
            TrangChuJFrame.this.dispose();
            new TamBietJDialog(this, true).setVisible(true);
        }
    }//GEN-LAST:event_mniKetThucActionPerformed

    private void mniDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDangXuatActionPerformed
        if (MsgBox.confirm(this, "Bạn thực sự muốn đăng xuất ?")) {
            new DangNhapJDialog(this, true).setVisible(true);
        }
    }//GEN-LAST:event_mniDangXuatActionPerformed

    private void btnDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangXuatActionPerformed
        mniDangXuatActionPerformed(evt);
    }//GEN-LAST:event_btnDangXuatActionPerformed

    private void btnKetThucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKetThucActionPerformed
        mniKetThucActionPerformed(evt);
    }//GEN-LAST:event_btnKetThucActionPerformed

    private void mniDoiMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDoiMatKhauActionPerformed
        new DoiMatKhauJDialog(this, true).setVisible(true);
    }//GEN-LAST:event_mniDoiMatKhauActionPerformed

    private void mniSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniSachActionPerformed
        new SachJDiaLog(this, true).setVisible(true);
    }//GEN-LAST:event_mniSachActionPerformed

    private void mniDonHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDonHangActionPerformed
        new DonHangJDialog(this, true).setVisible(true);
    }//GEN-LAST:event_mniDonHangActionPerformed

    private void mniDanhMucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDanhMucActionPerformed
        new DanhMucSachJDialog(this, true).setVisible(true);
    }//GEN-LAST:event_mniDanhMucActionPerformed

    private void mniNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniNhanVienActionPerformed
        if(Auth.isLogin()){
            if(!Auth.isManager()){
                MsgBox.alert(this, "Nhân viên không có quyền xem mục này!");
                return;
            }
            new NhanVienJDialog(this, true).setVisible(true);    
        }else{
                MsgBox.alert(this, "Bạn không có quyền xem mục này !");
        }              
    }//GEN-LAST:event_mniNhanVienActionPerformed

    private void btnTaiNguyenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaiNguyenActionPerformed
        mniSachActionPerformed(evt);
    }//GEN-LAST:event_btnTaiNguyenActionPerformed

    private void btnDonHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDonHangActionPerformed
        mniDonHangActionPerformed(evt);
    }//GEN-LAST:event_btnDonHangActionPerformed

    private void mniTopSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniTopSachActionPerformed
        openThongKe(0);
    }//GEN-LAST:event_mniTopSachActionPerformed

    private void mniDoanhThuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDoanhThuActionPerformed
        openThongKe(1);
    }//GEN-LAST:event_mniDoanhThuActionPerformed

    private void btnTopSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTopSachActionPerformed
        mniTopSachActionPerformed(evt);
    }//GEN-LAST:event_btnTopSachActionPerformed

    private void mniGioiThieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniGioiThieuActionPerformed
        new GioiThieuJDialog(this, true).setVisible(true);
    }//GEN-LAST:event_mniGioiThieuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrangChuJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrangChuJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrangChuJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrangChuJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TrangChuJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangXuat;
    private javax.swing.JButton btnDonHang;
    private javax.swing.JButton btnKetThuc;
    private javax.swing.JButton btnTaiNguyen;
    private javax.swing.JButton btnTopSach;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JToolBar.Separator jSeparator7;
    private javax.swing.JToolBar.Separator jSeparator8;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblDongHo;
    private javax.swing.JMenuItem mniDangXuat;
    private javax.swing.JMenuItem mniDanhMuc;
    private javax.swing.JMenuItem mniDoanhThu;
    private javax.swing.JMenuItem mniDoiMatKhau;
    private javax.swing.JMenuItem mniDonHang;
    private javax.swing.JMenuItem mniGioiThieu;
    private javax.swing.JMenuItem mniKetThuc;
    private javax.swing.JMenuItem mniNhanVien;
    private javax.swing.JMenuItem mniSach;
    private javax.swing.JMenuItem mniTopSach;
    private javax.swing.JMenu mnuGioiThieu;
    // End of variables declaration//GEN-END:variables

    private void init() {
        setSize(1000, 680);
        setLocationRelativeTo(null);
        this.setIconImage(XImage.getLogo());
        new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Date now = new Date();
                SimpleDateFormat formater = new SimpleDateFormat("hh:mm:ss a");
                String text = formater.format(now);
                lblDongHo.setText(text);
            }
        }).start();
        new KhoiDongJDialog(this, true).setVisible(true);
        new DangNhapJDialog(this, true).setVisible(true);
    }

    private void openThongKe(int index) {
         if(Auth.isLogin()){
            if(index == 1 && !Auth.isManager()){
                //xac dinh xem phải trưởng phòng không
                MsgBox.alert(this, "Bạn không có quyền xem Doanh thu!");
            }else{
                ThongKeJDialog tk = new ThongKeJDialog(this, true);
                tk.selectTab(index);
                tk.setVisible(true);  
                
            }
        }else{
            MsgBox.alert(this, "Vui lòng đăng nhập!");
        }
       
    }
}
